project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550 Final Project"
  page-footer:
    left: "chkim@design.upenn.edu"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/2_exploratory_analysis.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
